version: '3'
services:
  zookeeper-transaction:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: transaction-service-zookeeper
    ports:
      - "2182:2181"   # different external port than account-service
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-transaction:
    image: confluentinc/cp-kafka:7.5.0
    container_name: transaction-service-kafka
    depends_on:
      - zookeeper-transaction
    ports:
      - "9093:9092"   # different external port than account-service
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-transaction:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
